#!/bin/bash

#
# Configurations for dmenu
#

source "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.sh"

DMENU_WAL_THEME=(-nb $color0 -nf $color1 -sb $color2 -sf $color7 -fn "FantasqueSansMono Nerd Font:size=10")
DMENU_CENTER=(-l 20 -c -bw 5)
DMENU_BAR=(-h 18)

