#! /bin/sh

#############################
#                           #
#       * Settings *        #
#                           #
#############################

# Source colors
[ -f "~/.cache/wal/colors.sh" ] && . "$HOME/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle          true
bspc config right_padding           140
bspc config top_padding             10
bspc config focus_follows_pointer   true

bspc config active_border_color     "$color13"
bspc config normal_border_color     "$color0"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



#############################
#                           #
#   * Init Applications *   #
#                           #
#############################

# Start sxhkd
pgrep -x sxhkd > /dev/null && killall sxhkd
sxhkd &

# Set wallpaper
xwallpaper --output LVDS1 --stretch ~/Immagini/nord-wallpaper-arch.png

# Set cursor
xsetroot -cursor_name left_ptr

# Launch dunst
pgrep -x dunst > /dev/null && killall dunst

dunst -lf  "$color0" \
      -lb  "$color1" \
      -lfr "$color8" \
      -nf  "$color0" \
      -nb  "$color1" \
      -nfr "$color8" \
      -cf  "$color0" \
      -cb  "$color1" \
      -cfr "$color8" > /dev/null 2>&1 &


# Launch Lemonbar
pgrep -x lemonbar > /dev/null && killall lemonbar
~/.config/lemonbar/powerwalbar.sh

# Launch conky
pgrep -x conky > /dev/null && killall conky
conky --daemon

# Launch picom compositor
picom &

